<a href="https://colab.research.google.com/github/2303a51037/B1_PFDS_2303A51037/blob/main/lab_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print("mul",np.dot(a,b))
print("transpose:/n",np.linalg.inv(a))
print("determinant:",np.linalg.det(a))



mul [[19 22]
 [43 50]]
transpose:/n [[-2.   1. ]
 [ 1.5 -0.5]]
determinant: -2.0000000000000004


In [5]:
marks=np.random.randint(50,101,size=(5,4))
print(marks)
print("avg marks of student",np.mean(marks,axis=1))
print("avg marks of subject",np.mean(marks,axis=0))
print("student with highest total marks",np.max(np.sum(marks,axis=1)))
print("subject with lowest total marks",np.min(np.sum(marks,axis=0)))

[[67 61 83 55]
 [94 89 58 64]
 [99 71 89 92]
 [65 65 71 54]
 [72 87 82 52]]
avg marks of student [66.5  76.25 87.75 63.75 73.25]
avg marks of subject [79.4 74.6 76.6 63.4]
student with highest total marks 351
subject with lowest total marks 317


In [7]:
import pandas as pd
data=[10,20,30,40,50]
index_labels=['a','b','c','d','e']
series=pd.Series(data,index=index_labels)
print(series)

a    10
b    20
c    30
d    40
e    50
dtype: int64


In [14]:
import pandas as pd
data={
    'Name':['Alice','Bob','Charlie','rama'],
    'Age':[25,30,35,18],
    'City':['New York','San Francisco','Los Angeles','hnk']
}
df=pd.DataFrame(data)
print("Pandas DataFrame:")
print(df)
print(df[['Name','City']])
print(df.iloc[1])
print(df.loc[2])
df=df.drop('City',axis=1)
print(df)
print(df[df['Age']>30])
print(df['Age'].mean())
print(df['Age'].max())
print(df['Age'].min())
print(df.sort_values(by='Age'))



Pandas DataFrame:
      Name  Age           City
0    Alice   25       New York
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles
3     rama   18            hnk
      Name           City
0    Alice       New York
1      Bob  San Francisco
2  Charlie    Los Angeles
3     rama            hnk
Name              Bob
Age                30
City    San Francisco
Name: 1, dtype: object
Name        Charlie
Age              35
City    Los Angeles
Name: 2, dtype: object
      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3     rama   18
      Name  Age
2  Charlie   35
27.0
35
18
      Name  Age
3     rama   18
0    Alice   25
1      Bob   30
2  Charlie   35
-------------------------------------------------------------------


In [18]:
import pandas as pd
student_data = {
    'Student_ID': ['1001', '1002', '1003', '1004'],
    'Name':['rama','neha','kiran','sita'],

    'Marks': [50,99, 70, 21],
    'Department': ['CSE','ECE','MECH','CIVIL']
}
df = pd.DataFrame(student_data)
print("Student Data")
print("\nStudents with Marks>80")
print(df[df['Marks']>80])
print("\nAverage Marks",df['Marks'].mean())
df['Result']=['Pass' if x>40 else 'Fail' for x in df['Marks']]
print("\nWith Result Column")
print(df)

Student Data

Students with Marks>80
  Student_ID  Name  Marks Department
1       1002  neha     99        ECE

Average Marks 60.0

With Result Column
  Student_ID   Name  Marks Department Result
0       1001   rama     50        CSE   Pass
1       1002   neha     99        ECE   Pass
2       1003  kiran     70       MECH   Pass
3       1004   sita     21      CIVIL   Fail
